### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:libtensorflow_framework.os:cannot open shared object file:No such file or directory

### ISSUE THREAD

**Issue by zoupei123456** [ronghanghu/tensorflow_compact_bilinear_pooling#7]
Hello, when I run compact_bilinear_pooling_test, the following error occurs. Can you tell me what is going on?

File "D:/jupyter/tensorflow_compact_bilinear_pooling-master/compact_bilinear_pooling_test.py", line 5, in 
from compact_bilinear_pooling import compact_bilinear_pooling_layer
File "D:\jupyter\tensorflow_compact_bilinear_pooling-master\compact_bilinear_pooling.py", line 6, in 
from sequential_fft import sequential_batch_fft, sequential_batch_ifft
File "D:\jupyter\tensorflow_compact_bilinear_pooling-master\sequential_fft_init_.py", line 1, in 
from .sequential_batch_fft_ops import sequential_batch_fft, sequential_batch_ifft
File "D:\jupyter\tensorflow_compact_bilinear_pooling-master\sequential_fft\sequential_batch_fft_ops.py", line 10, in 
'build/sequential_batch_fft.so'))
File "C:\Users\window10\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 56, in load_op_library
lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError:libtensorflow_framework.os:cannot open shared object file:No such file or directory

**Comment by ronghanghu** [comment]
Hi, the provided built binary was for Linux, and a few changes are needed to run it on Windows:

If the steps below don't work for you, you can try changing to `sequential=False` in https://github.com/ronghanghu/tensorflow_compact_bilinear_pooling/blob/master/compact_bilinear_pooling.py#L49, which uses the existing TensorFlow FFT option, but requires much larger GPU memory.

Steps to run on Windows:
1. Create a compile script for Windows using your C++ compiler (such as Visual C++ or MinGW) and CUDA NVCC similar to the Linux compile script: https://github.com/ronghanghu/tensorflow_compact_bilinear_pooling/blob/master/sequential_fft/compile.sh. After this step, you should be able to compile a Windows shared library `sequential_batch_fft.dll` under sequential_fft/build/.
2. Change the dynamic library path from `'build/sequential_batch_fft.so'` (for Linux) to `'build\\sequential_batch_fft.dll'` (for Windows) in
https://github.com/ronghanghu/tensorflow_compact_bilinear_pooling/blob/master/sequential_fft/sequential_batch_fft_ops.py#L10

**Comment by zoupei123456** [comment]
I'm running in Linux, tensorflow 1.0.0, cuda8, g++ 4.8.4, compact_bilinear_pooling_test.py or sequential_batch_fft_test.py, and I see this error.
/usr/bin/python3zp /media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/compact_bilinear_pooling_test.py
Traceback (most recent call last):
  File "/media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/compact_bilinear_pooling_test.py", line 5, in <module>
    from compact_bilinear_pooling import compact_bilinear_pooling_layer
  File "/media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/compact_bilinear_pooling.py", line 6, in <module>
    from sequential_fft import sequential_batch_fft, sequential_batch_ifft
  File "/media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/sequential_fft/__init__.py", line 1, in <module>
    from .sequential_batch_fft_ops import sequential_batch_fft, sequential_batch_ifft
  File "/media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/sequential_fft/sequential_batch_fft_ops.py", line 11, in <module>
    'build/sequential_batch_fft.so'))
  File "/home/vip/Zoupei/python3zp/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/sequential_fft/build/sequential_batch_fft.so: undefined symbol: _Z23SequentialFFTCUDAKernelPKSt7complexIfEiiibPS0_

**Comment by zoupei123456** [comment]
When I rebuild sequential_batch_fft.so with compile.sh in sequential_fft/, using the same CUDA version and C++ compiler. I got the following error：
vip@vip-vip:/media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master$ sh ./sequential_fft/compile.sh
gcc: error: sequential_batch_fft_kernel.cu.cc: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
g++: error: sequential_batch_fft_kernel.cu.o: No such file or directory
g++: error: sequential_batch_fft.cc: No such file or directory

**Comment by ronghanghu** [comment]
To compile it, first `cd sequential_fft/` and then `./compile.sh`.

The error above (undefined symbol: Z23SequentialFFTCUDAKernelPKSt7complexIfEiiibPS0) seems to come from GCC 4.x vs 5.x mismatch in ABI (https://docs.computecanada.ca/wiki/GCC_C%2B%2B_Dual_ABI). You can try switching to `-D_GLIBCXX_USE_CXX11_ABI=1` in compile.sh

**Comment by zoupei123456** [comment]
Thanks for the advice, I can now run the program you provided, but when I run sequential_batch_fft_test.py, I get the following error.Can you tell me what is going on?
/usr/bin/python3.5 /media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/sequential_fft/sequential_batch_fft_test.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/media/vip/Data2/zoupei/tensorflow_compact_bilinear_pooling-master/sequential_fft/sequential_batch_fft_test.py", line 21, in <module>
    gx_fft = tf.gradients(x_fft, x)[0]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 526, in _GradientsHelper
    gradient_uid)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 245, in _DefaultGradYs
    y.dtype)
TypeError: Gradients of complex tensors must set grad_ys (y.dtype = tf.complex64)

**Comment by zoupei123456** [comment]
When I added the compact_bilinear_pooling layer to my network, I found that the output dimension is (?,?). This can't directly connect to the fully connected layer. What is going on? There is no error reporting when running compact_bilinear_pooling_test.py. What should I do this, please tell me, I will thank you very much.

**Comment by ronghanghu** [comment]
Regarding the shape issue, you can explicitly set the shape information by calling `set_shape()`. For example:
```
output.set_shape([None, output_dim])
```
Details in https://www.tensorflow.org/api_docs/python/tf/Tensor?hl=en#set_shape

**Comment by ronghanghu** [comment]
I guess the previous error in sequential_batch_fft_test is due to a change in TF interface. I'll look into it.

Edit: it's due to a TF API change in https://github.com/benoitsteiner/tensorflow/commit/c2223f03c239d6d68f9452037b6d009255c83d00. I've fixed it in https://github.com/ronghanghu/tensorflow_compact_bilinear_pooling/commit/8c7a0cd3b73767e4c1b98ed59120a1d82efa9862
(this only affects the sequential_batch_fft_test; it doesn't affect the compact bilinear pooling results).

**Comment by zoupei123456** [comment]
Thank you very much for your help. Now I can use the compact_bilinear_pooling layer in my network framework. I hope this can help improve my network performance.Thanks again for your help. Thank you very much

**Comment by ronghanghu** [comment]
Glad to hear that it helped you!
