### ISSUE TITLE
compile.sh can not find "-ltensorflow_framework"

### ISSUE THREAD

**Issue by limt15** [ronghanghu/tensorflow_compact_bilinear_pooling#8]
dear author,
thank you for your implementation. 
when I build the project against tensorflow version 1.3.0 and CUDA 8.0 python2.7 on Ubuntu16.04. Program error：/usr/bin/ld: cannot find -ltensorflow_framework
when I build the project against tensorflow version 1.0.0 and CUDA 8.0 python2.7 on Ubuntu16.04. The Same Program error：/usr/bin/ld: cannot find -ltensorflow_framework

can you help me to solve this problem?

**Comment by ronghanghu** [comment]
Hi, this `-ltensorflow_framework` is introduced for newer TensorFlow version (e.g. 1.12). If you use TensorFlow 1.0.0, you can simply remove this `-ltensorflow_framework` flag in compile.sh.

**Comment by limt15** [comment]
Thank you very much for your reply！
I have to build the project against tensorflow version 1.3.0，CUDA 8.0， python2.7 on Ubuntu16.04. 
But when I removed the -ltensorflow_framework flag  of the compile.sh in this way:      
`# -L$TF_LIB  -ltensorflow_framework `

The program has the same error below：
  
`compile.sh: line 8: -I: command not found`
`sequential_batch_fft.cc:1:42:  fatal error: tensorflow/core/framework/op.h: No such file or directory`
`compilation  terminated.`
`compile.sh: line 15: -I: command not found`

can you help me to solve this problem?

**Comment by ronghanghu** [comment]
Hi, instead of commenting this line with a hashtag `#`, you need to **remove** this line, or add a backslash `\` at the end of the line after the comment.

**Comment by brianlen** [comment]
@ronghanghu 

Do you mean delete: `-L$TF_LIB -ltensorflow_framework` or delete only `-ltensorflow_framework` ?

How do I know if .so file successfully compiled?
